package templatelearn

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"sync"
	"time"
)

// FeedbackType classifies feedback
type FeedbackType string

const (
	FeedbackFalsePositive FeedbackType = "false_positive"
	FeedbackTruePositive  FeedbackType = "true_positive"
	FeedbackFalseNegative FeedbackType = "false_negative"
)

// Feedback represents user feedback on a finding
type Feedback struct {
	ID           string       `json:"id"`            // unique ID (hash of template+host+matcher)
	TemplateID   string       `json:"template_id"`   // nuclei template ID
	Host         string       `json:"host"`          // target host
	MatcherName  string       `json:"matcher_name"`  // matched matcher name
	VulnType     string       `json:"vuln_type"`     // inferred vuln type
	Type         FeedbackType `json:"type"`          // FP, TP, or FN
	Reason       string       `json:"reason"`        // user explanation
	UserNote     string       `json:"user_note"`     // optional user note
	Timestamp    time.Time    `json:"timestamp"`
	Count        int          `json:"count"`         // how many times this feedback was given
	AutoSuppressed bool       `json:"auto_suppressed"` // true if auto-suppressed by threshold
}

// SuppressionRule defines when findings should be suppressed
type SuppressionRule struct {
	ID            string   `json:"id"`
	TemplateID    string   `json:"template_id"`    // empty = applies to all
	Host          string   `json:"host"`           // empty = applies to all hosts
	MatcherName   string   `json:"matcher_name"`   // empty = all matchers
	VulnType      string   `json:"vuln_type"`      // empty = all types
	Reason        string   `json:"reason"`
	FPTreshold    int      `json:"fp_threshold"`   // auto-suppress after N FP marks
	CreatedAt     time.Time `json:"created_at"`
	AutoGenerated bool     `json:"auto_generated"` // true if created by auto-learning
}

// FindingSignature creates a unique hash for a finding
type FindingSignature struct {
	Hash       string
	TemplateID string
	Host       string
	Matcher    string
}

// SignatureFromFinding creates a signature from finding fields
func SignatureFromFinding(templateID, host, matcherName string) FindingSignature {
	raw := fmt.Sprintf("%s|%s|%s", templateID, host, matcherName)
	h := sha256.Sum256([]byte(strings.ToLower(raw)))
	return FindingSignature{
		Hash:       hex.EncodeToString(h[:16]),
		TemplateID: templateID,
		Host:       host,
		Matcher:    matcherName,
	}
}

// FeedbackStore stores feedback and suppression rules persistently
type FeedbackStore struct {
	feedback    map[string]*Feedback       // keyed by feedback ID
	suppressions map[string]*SuppressionRule // keyed by rule ID
	mu          sync.RWMutex
	filePath    string
	autoThreshold int // auto-suppress after this many FP marks
}

// NewFeedbackStore creates a new store
func NewFeedbackStore(filePath string, autoThreshold int) *FeedbackStore {
	if autoThreshold <= 0 {
		autoThreshold = 3
	}
	return &FeedbackStore{
		feedback:     make(map[string]*Feedback),
		suppressions: make(map[string]*SuppressionRule),
		filePath:     filePath,
		autoThreshold: autoThreshold,
	}
}

// MarkFeedback records feedback for a finding
func (s *FeedbackStore) MarkFeedback(templateID, host, matcherName, vulnType string, ftype FeedbackType, reason, note string) *Feedback {
	s.mu.Lock()
	defer s.mu.Unlock()

	sig := SignatureFromFinding(templateID, host, matcherName)
	id := sig.Hash

	if existing, ok := s.feedback[id]; ok {
		existing.Count++
		existing.Type = ftype
		if reason != "" {
			existing.Reason = reason
		}
		if note != "" {
			existing.UserNote = note
		}
		existing.Timestamp = time.Now()
		// Check auto-suppression
		if ftype == FeedbackFalsePositive && existing.Count >= s.autoThreshold {
			existing.AutoSuppressed = true
			s.addAutoSuppressionRule(existing)
		}
		return existing
	}

	fb := &Feedback{
		ID:          id,
		TemplateID:  templateID,
		Host:        host,
		MatcherName: matcherName,
		VulnType:    vulnType,
		Type:        ftype,
		Reason:      reason,
		UserNote:    note,
		Timestamp:   time.Now(),
		Count:       1,
	}
	s.feedback[id] = fb

	// Check auto-suppression on first mark
	if ftype == FeedbackFalsePositive && s.autoThreshold <= 1 {
		fb.AutoSuppressed = true
		s.addAutoSuppressionRule(fb)
	}

	return fb
}

// addAutoSuppressionRule creates a suppression rule from feedback (must be called with lock held)
func (s *FeedbackStore) addAutoSuppressionRule(fb *Feedback) {
	rule := &SuppressionRule{
		ID:            fmt.Sprintf("auto-%s", fb.ID),
		TemplateID:    fb.TemplateID,
		Host:          fb.Host,
		MatcherName:   fb.MatcherName,
		VulnType:      fb.VulnType,
		Reason:        fmt.Sprintf("Auto-suppressed: %d FP marks — %s", fb.Count, fb.Reason),
		FPTreshold:    s.autoThreshold,
		CreatedAt:     time.Now(),
		AutoGenerated: true,
	}
	s.suppressions[rule.ID] = rule
}

// AddSuppressionRule manually adds a suppression rule
func (s *FeedbackStore) AddSuppressionRule(rule *SuppressionRule) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if rule.ID == "" {
		rule.ID = fmt.Sprintf("manual-%d", time.Now().UnixNano())
	}
	if rule.CreatedAt.IsZero() {
		rule.CreatedAt = time.Now()
	}
	s.suppressions[rule.ID] = rule
}

// ShouldSuppress checks if a finding should be suppressed
func (s *FeedbackStore) ShouldSuppress(templateID, host, matcherName, vulnType string) (bool, string) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	for _, rule := range s.suppressions {
		if rule.TemplateID != "" && !strings.EqualFold(rule.TemplateID, templateID) {
			continue
		}
		if rule.Host != "" && !strings.EqualFold(rule.Host, host) {
			continue
		}
		if rule.MatcherName != "" && !strings.EqualFold(rule.MatcherName, matcherName) {
			continue
		}
		if rule.VulnType != "" && !strings.EqualFold(rule.VulnType, vulnType) {
			continue
		}
		return true, rule.Reason
	}
	return false, ""
}

// GetFeedback returns feedback by ID
func (s *FeedbackStore) GetFeedback(id string) *Feedback {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.feedback[id]
}

// GetAllFeedback returns all feedback entries
func (s *FeedbackStore) GetAllFeedback() []*Feedback {
	s.mu.RLock()
	defer s.mu.RUnlock()
	result := make([]*Feedback, 0, len(s.feedback))
	for _, fb := range s.feedback {
		result = append(result, fb)
	}
	return result
}

// GetAllSuppressions returns all suppression rules
func (s *FeedbackStore) GetAllSuppressions() []*SuppressionRule {
	s.mu.RLock()
	defer s.mu.RUnlock()
	result := make([]*SuppressionRule, 0, len(s.suppressions))
	for _, rule := range s.suppressions {
		result = append(result, rule)
	}
	return result
}

// RemoveSuppression removes a suppression rule by ID
func (s *FeedbackStore) RemoveSuppression(ruleID string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, ok := s.suppressions[ruleID]; ok {
		delete(s.suppressions, ruleID)
		return true
	}
	return false
}

// FeedbackStats holds statistics about the feedback store
type FeedbackStats struct {
	TotalFeedback      int
	FalsePositives     int
	TruePositives      int
	FalseNegatives     int
	AutoSuppressed     int
	ManualSuppressions int
	UniqueTemplates    int
	UniqueHosts        int
}

// Stats returns statistics about the feedback store
func (s *FeedbackStore) Stats() FeedbackStats {
	s.mu.RLock()
	defer s.mu.RUnlock()

	stats := FeedbackStats{TotalFeedback: len(s.feedback)}
	templates := make(map[string]bool)
	hosts := make(map[string]bool)

	for _, fb := range s.feedback {
		templates[fb.TemplateID] = true
		hosts[fb.Host] = true
		switch fb.Type {
		case FeedbackFalsePositive:
			stats.FalsePositives++
			if fb.AutoSuppressed {
				stats.AutoSuppressed++
			}
		case FeedbackTruePositive:
			stats.TruePositives++
		case FeedbackFalseNegative:
			stats.FalseNegatives++
		}
	}

	for _, rule := range s.suppressions {
		if !rule.AutoGenerated {
			stats.ManualSuppressions++
		}
	}

	stats.UniqueTemplates = len(templates)
	stats.UniqueHosts = len(hosts)
	return stats
}
